<?php
use BaftFeedback\Listener\BaftFeedbackRouteListener;
foreach ( $form->getElements () as &$element ) {
	$element->setAttribute ( 'class', 'form-control' );
	$element->setOptions ( [
			'label_attributes' => [
					'class' => 'display-block'
			]
	] );
}
$form->setOptions ( [
		'form_attributes' => [
				'enctype' => 'multipart/form-data',
				'action' => '',
				'method' => 'POST'
		]
] );

$form->add ( array (
		'name' => 'submit',
		'attributes' => array (
				'type' => 'submit',
				'value' => 'Send',
				'class' => 'btn btn-success'
		)
) );

echo $this->form ()->openTag ( $form );
echo $this->formCollection ( $form );
?>
<div class="align-left float-left">
	<a class="btn btn-success"
		href="<?php

		print $this->url (  'main/general', [
				"__NAMESPACE__" => 'BaftFeedback',
				"controller" => 'admin',
				'action' => 'listFeedback'
		] );
		?>">Cancel</a>
</div>
<div class="clear-both"></div>
<?php
echo $this->form ()->closeTag ();
?>